version: "3.3"
services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: astro_vue
    ports:
      - "3511:3000"
    environment:
      - TZ=Europe/Berlin
      - NODE_ENV=development
    volumes:
      - .:/app
    tty: true # -t flag
    stdin_open: true # -i flag
    restart: unless-stopped

    ulimits:
      nproc: 65535
